package com.redpoint.groupchatapp;


import client.MobileController;

import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;

import gui.panels.mainmenu.MainMenuController;

import java.io.IOException;

import server.FakeLocalServer;


/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class GroupChatApp {

    private Form current;
    private Resources theme;
    
    private MobileController mobileController;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
        
        mobileController = new MobileController(new FakeLocalServer());

    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        
       mobileController.startGui();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    	//TODO figure out how we should do this. Probably close all connections to the server, logout, etc.
    }

}
